2024-04-13 11:08:16,584 - main - ERROR - 19 - Testing 1
Traceback (most recent call last):
  File "D:\automated_scripts\main.py", line 16, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2024-04-13 11:09:50,346 - main - ERROR - 18 - Testing 1
Traceback (most recent call last):
  File "D:\automated_scripts\main.py", line 15, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2024-04-13 11:13:01,985 - main - ERROR - 18 - Testing 1
Traceback (most recent call last):
  File "D:\automated_scripts\main.py", line 15, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2024-04-13 11:23:15,624 - main - ERROR - 18 - Testing 1
Traceback (most recent call last):
  File "D:\automated_scripts\main.py", line 15, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2024-04-13 11:23:42,609 - main - INFO - 16 - Divison worked
2024-04-13 12:00:10,273 - main - ERROR - 18 - Testing 1
Traceback (most recent call last):
  File "D:\automated_scripts\main.py", line 15, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2024-04-13 12:01:28,480 - main - ERROR - 18 - Testing 1
Traceback (most recent call last):
  File "D:\automated_scripts\main.py", line 15, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2024-04-13 12:03:12,457 - main - ERROR - 18 - Testing 1
Traceback (most recent call last):
  File "D:\automated_scripts\main.py", line 15, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2024-04-13 12:09:18,482 - main - ERROR - 18 - Testing 1
Traceback (most recent call last):
  File "D:\automated_scripts\main.py", line 15, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2024-04-13 12:09:52,535 - main - ERROR - 18 - Testing 1
Traceback (most recent call last):
  File "D:\automated_scripts\main.py", line 15, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2024-04-13 12:11:39,393 - main - ERROR - 18 - Testing 1
Traceback (most recent call last):
  File "D:\automated_scripts\main.py", line 15, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2024-04-13 12:14:10,857 - main - ERROR - 18 - Testing 1
Traceback (most recent call last):
  File "D:\automated_scripts\main.py", line 15, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
2024-04-13 12:44:55,820 - main - ERROR - 19 - Testing 1
Traceback (most recent call last):
  File "D:\automated_scripts\main.py", line 16, in <module>
    1/0
    ~^~
ZeroDivisionError: division by zero
